#include "cpu.h"
#include <iostream>


cpu::cpu()
{ 
    ins_table = {
        //                       0                                1                               2                               3                                 4                               5                               6                              7                                   8                            9                               A                                 B                             C                                D                                E                               F                                
        /* 0 */ { &cpu::BRK, &cpu::add_IMP, 7 },{ &cpu::ORA, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SLO, &cpu::add_iIND, 8 },{ &cpu::NOP, &cpu::add_ZP0, 3 },{ &cpu::ORA, &cpu::add_ZP0, 3 },{ &cpu::ASL, &cpu::add_ZP0, 5 },{ &cpu::SLO, &cpu::add_ZP0, 5 },{ &cpu::PHP, &cpu::add_IMP, 3 },{ &cpu::ORA, &cpu::add_IMM, 2 },{ &cpu::ASL, &cpu::add_IMP, 2 },{ &cpu::ANC, &cpu::add_IMP, 2 },{ &cpu::NOP, &cpu::add_ABS, 4 },{ &cpu::ORA, &cpu::add_ABS, 4 },{ &cpu::ASL, &cpu::add_ABS, 6 },{ &cpu::SLO, &cpu::add_ABS, 6 },
        /* 1 */ { &cpu::BPL, &cpu::add_REL, 2 },{ &cpu::ORA, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SLO, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::ORA, &cpu::add_ZPX, 4 },{ &cpu::ASL, &cpu::add_ZPX, 6 },{ &cpu::SLO, &cpu::add_ZPX, 6 },{ &cpu::CLC, &cpu::add_IMP, 2 },{ &cpu::ORA, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SLO, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::ORA, &cpu::add_ABX, 4 },{ &cpu::ASL, &cpu::add_ABX, 7 },{ &cpu::SLO, &cpu::add_ABX, 7 },
        /* 2 */ { &cpu::JSR, &cpu::add_ABS, 6 },{ &cpu::AND, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RLA, &cpu::add_iIND, 8 },{ &cpu::BIT, &cpu::add_ZP0, 3 },{ &cpu::AND, &cpu::add_ZP0, 3 },{ &cpu::ROL, &cpu::add_ZP0, 5 },{ &cpu::RLA, &cpu::add_ZP0, 5 },{ &cpu::PLP, &cpu::add_IMP, 4 },{ &cpu::AND, &cpu::add_IMM, 2 },{ &cpu::ROL, &cpu::add_IMP, 2 },{ &cpu::ANC, &cpu::add_IMP, 2 },{ &cpu::BIT, &cpu::add_ABS, 4 },{ &cpu::AND, &cpu::add_ABS, 4 },{ &cpu::ROL, &cpu::add_ABS, 6 },{ &cpu::RLA, &cpu::add_ABS, 6 },
        /* 3 */	{ &cpu::BMI, &cpu::add_REL, 2 },{ &cpu::AND, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RLA, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::AND, &cpu::add_ZPX, 4 },{ &cpu::ROL, &cpu::add_ZPX, 6 },{ &cpu::RLA, &cpu::add_ZPX, 6 },{ &cpu::SEC, &cpu::add_IMP, 2 },{ &cpu::AND, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::RLA, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::AND, &cpu::add_ABX, 4 },{ &cpu::ROL, &cpu::add_ABX, 7 },{ &cpu::RLA, &cpu::add_ABX, 7 },
        /* 4 */	{ &cpu::RTI, &cpu::add_IMP, 6 },{ &cpu::EOR, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SRE, &cpu::add_iIND, 8 },{ &cpu::NOP, &cpu::add_ZP0, 3 },{ &cpu::EOR, &cpu::add_ZP0, 3 },{ &cpu::LSR, &cpu::add_ZP0, 5 },{ &cpu::SRE, &cpu::add_ZP0, 5 },{ &cpu::PHA, &cpu::add_IMP, 3 },{ &cpu::EOR, &cpu::add_IMM, 2 },{ &cpu::LSR, &cpu::add_IMP, 2 },{ &cpu::ALR, &cpu::add_IMP, 2 },{ &cpu::JMP, &cpu::add_ABS, 3 },{ &cpu::EOR, &cpu::add_ABS, 4 },{ &cpu::LSR, &cpu::add_ABS, 6 },{ &cpu::SRE, &cpu::add_ABS, 6 },
        /* 5 */ { &cpu::BVC, &cpu::add_REL, 2 },{ &cpu::EOR, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SRE, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::EOR, &cpu::add_ZPX, 4 },{ &cpu::LSR, &cpu::add_ZPX, 6 },{ &cpu::SRE, &cpu::add_ZPX, 6 },{ &cpu::CLI, &cpu::add_IMP, 2 },{ &cpu::EOR, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SRE, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::EOR, &cpu::add_ABX, 4 },{ &cpu::LSR, &cpu::add_ABX, 7 },{ &cpu::SRE, &cpu::add_ABX, 7 },
        /* 6 */	{ &cpu::RTS, &cpu::add_IMP, 6 },{ &cpu::ADC, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RRA, &cpu::add_iIND, 8 },{ &cpu::NOP, &cpu::add_ZP0, 3 },{ &cpu::ADC, &cpu::add_ZP0, 3 },{ &cpu::ROR, &cpu::add_ZP0, 5 },{ &cpu::RRA, &cpu::add_ZP0, 5 },{ &cpu::PLA, &cpu::add_IMP, 4 },{ &cpu::ADC, &cpu::add_IMM, 2 },{ &cpu::ROR, &cpu::add_IMP, 2 },{ &cpu::ARR, &cpu::add_IMP, 2 },{ &cpu::JMP, &cpu::add_IND, 5 },{ &cpu::ADC, &cpu::add_ABS, 4 },{ &cpu::ROR, &cpu::add_ABS, 6 },{ &cpu::RRA, &cpu::add_ABS, 6 },
        /* 7 */	{ &cpu::BVS, &cpu::add_REL, 2 },{ &cpu::ADC, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RRA, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::ADC, &cpu::add_ZPX, 4 },{ &cpu::ROR, &cpu::add_ZPX, 6 },{ &cpu::RRA, &cpu::add_ZPX, 6 },{ &cpu::SEI, &cpu::add_IMP, 2 },{ &cpu::ADC, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::RRA, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::ADC, &cpu::add_ABX, 4 },{ &cpu::ROR, &cpu::add_ABX, 7 },{ &cpu::RRA, &cpu::add_ABX, 7 },
        /* 8 */	{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::STA, &cpu::add_iIND, 6 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SAX, &cpu::add_IMP, 6 }, { &cpu::STY, &cpu::add_ZP0, 3 },{ &cpu::STA, &cpu::add_ZP0, 3 },{ &cpu::STX, &cpu::add_ZP0, 3 },{ &cpu::SAX, &cpu::add_ZP0, 3 },{ &cpu::DEY, &cpu::add_IMP, 2 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::TXA, &cpu::add_IMP, 2 },{ &cpu::ANE, &cpu::add_IMP, 2 },{ &cpu::STY, &cpu::add_ABS, 4 },{ &cpu::STA, &cpu::add_ABS, 4 },{ &cpu::STX, &cpu::add_ABS, 4 },{ &cpu::SAX, &cpu::add_ABS, 4 },
        /* 9 */	{ &cpu::BCC, &cpu::add_REL, 2 },{ &cpu::STA, &cpu::add_INDi, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SHA, &cpu::add_IMP, 6 }, { &cpu::STY, &cpu::add_ZPX, 4 },{ &cpu::STA, &cpu::add_ZPX, 4 },{ &cpu::STX, &cpu::add_ZPY, 4 },{ &cpu::SAX, &cpu::add_ZPX, 4 },{ &cpu::TYA, &cpu::add_IMP, 2 },{ &cpu::STA, &cpu::add_ABY, 5 },{ &cpu::TXS, &cpu::add_IMP, 2 },{ &cpu::TAS, &cpu::add_ABY, 5 },{ &cpu::SHY, &cpu::add_ABX, 5 },{ &cpu::STA, &cpu::add_ABX, 5 },{ &cpu::SHX, &cpu::add_ABY, 5 },{ &cpu::SHA, &cpu::add_ABY, 5 },
        /* A */	{ &cpu::LDY, &cpu::add_IMM, 2 },{ &cpu::LDA, &cpu::add_iIND, 6 },{ &cpu::LDX, &cpu::add_IMM, 2 },{ &cpu::LAX, &cpu::add_IMP, 6 }, { &cpu::LDY, &cpu::add_ZP0, 3 },{ &cpu::LDA, &cpu::add_ZP0, 3 },{ &cpu::LDX, &cpu::add_ZP0, 3 },{ &cpu::LAX, &cpu::add_ZP0, 3 },{ &cpu::TAY, &cpu::add_IMP, 2 },{ &cpu::LDA, &cpu::add_IMM, 2 },{ &cpu::TAX, &cpu::add_IMP, 2 },{ &cpu::LXA, &cpu::add_IMP, 2 },{ &cpu::LDY, &cpu::add_ABS, 4 },{ &cpu::LDA, &cpu::add_ABS, 4 },{ &cpu::LDX, &cpu::add_ABS, 4 },{ &cpu::LAX, &cpu::add_ABS, 4 },
        /* B */	{ &cpu::BCS, &cpu::add_REL, 2 },{ &cpu::LDA, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::LAX, &cpu::add_IMP, 5 }, { &cpu::LDY, &cpu::add_ZPX, 4 },{ &cpu::LDA, &cpu::add_ZPX, 4 },{ &cpu::LDX, &cpu::add_ZPY, 4 },{ &cpu::LAX, &cpu::add_ZPX, 4 },{ &cpu::CLV, &cpu::add_IMP, 2 },{ &cpu::LDA, &cpu::add_ABY, 4 },{ &cpu::TSX, &cpu::add_IMP, 2 },{ &cpu::LAS, &cpu::add_ABY, 4 },{ &cpu::LDY, &cpu::add_ABX, 4 },{ &cpu::LDA, &cpu::add_ABX, 4 },{ &cpu::LDX, &cpu::add_ABY, 4 },{ &cpu::LAX, &cpu::add_ABY, 4 },
        /* C */	{ &cpu::CPY, &cpu::add_IMM, 2 },{ &cpu::CMP, &cpu::add_iIND, 6 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::DCP, &cpu::add_IMP, 8 }, { &cpu::CPY, &cpu::add_ZP0, 3 },{ &cpu::CMP, &cpu::add_ZP0, 3 },{ &cpu::DEC, &cpu::add_ZP0, 5 },{ &cpu::DCP, &cpu::add_ZP0, 5 },{ &cpu::INY, &cpu::add_IMP, 2 },{ &cpu::CMP, &cpu::add_IMM, 2 },{ &cpu::DEX, &cpu::add_IMP, 2 },{ &cpu::SBX, &cpu::add_IMP, 2 },{ &cpu::CPY, &cpu::add_ABS, 4 },{ &cpu::CMP, &cpu::add_ABS, 4 },{ &cpu::DEC, &cpu::add_ABS, 6 },{ &cpu::DCP, &cpu::add_ABS, 6 },
        /* D */	{ &cpu::BNE, &cpu::add_REL, 2 },{ &cpu::CMP, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::DCP, &cpu::add_IMP, 8 }, { &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::CMP, &cpu::add_ZPX, 4 },{ &cpu::DEC, &cpu::add_ZPX, 6 },{ &cpu::DCP, &cpu::add_ZPX, 6 },{ &cpu::CLD, &cpu::add_IMP, 2 },{ &cpu::CMP, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::DCP, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::CMP, &cpu::add_ABX, 4 },{ &cpu::DEC, &cpu::add_ABX, 7 },{ &cpu::DCP, &cpu::add_ABX, 7 },
        /* E */	{ &cpu::CPX, &cpu::add_IMM, 2 },{ &cpu::SBC, &cpu::add_iIND, 6 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::ISC, &cpu::add_IMP, 8 }, { &cpu::CPX, &cpu::add_ZP0, 3 },{ &cpu::SBC, &cpu::add_ZP0, 3 },{ &cpu::INC, &cpu::add_ZP0, 5 },{ &cpu::ISC, &cpu::add_ZP0, 5 },{ &cpu::INX, &cpu::add_IMP, 2 },{ &cpu::SBC, &cpu::add_IMM, 2 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SBC, &cpu::add_IMP, 2 },{ &cpu::CPX, &cpu::add_ABS, 4 },{ &cpu::SBC, &cpu::add_ABS, 4 },{ &cpu::INC, &cpu::add_ABS, 6 },{ &cpu::ISC, &cpu::add_ABS, 6 },
        /* F */	{ &cpu::BEQ, &cpu::add_REL, 2 },{ &cpu::SBC, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::ISC, &cpu::add_IMP, 8 }, { &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::SBC, &cpu::add_ZPX, 4 },{ &cpu::INC, &cpu::add_ZPX, 6 },{ &cpu::ISC, &cpu::add_ZPX, 6 },{ &cpu::SED, &cpu::add_IMP, 2 },{ &cpu::SBC, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::ISC, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::SBC, &cpu::add_ABX, 4 },{ &cpu::INC, &cpu::add_ABX, 7 },{ &cpu::ISC, &cpu::add_ABX, 7 },

        //REMEMBER  A-0,2,4,6  ADD MODE A CHECK INSTRUCTION TABLE WEBSITE     
        };

}

cpu::~cpu()
{
 //Destructor
}

// Function Defintions Start Here..............




int main()
{

    std::cout <<"compiled successfully"<< std::endl;
return 0;
}


  

// ins_table = {
//         //                       0                                1                               2                               3                                 4                               5                               6                              7                                   8                            9                               A                                 B                             C                                D                                E                               F                                
//         /* 0 */ { &cpu::BRK, &cpu::add_IMP, 7 },{ &cpu::ORA, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SLO, &cpu::add_iIND, 8 },{ &cpu::NOP, &cpu::add_ZP0, 3 },{ &cpu::ORA, &cpu::add_ZP0, 3 },{ &cpu::ASL, &cpu::add_ZP0, 5 },{ &cpu::SLO, &cpu::add_ZP0, 5 },{ &cpu::PHP, &cpu::add_IMP, 3 },{ &cpu::ORA, &cpu::add_IMM, 2 },{ &cpu::ASL, &cpu::add_IMP, 2 },{ &cpu::ANC, &cpu::add_IMP, 2 },{ &cpu::NOP, &cpu::add_ABS, 4 },{ &cpu::ORA, &cpu::add_ABS, 4 },{ &cpu::ASL, &cpu::add_ABS, 6 },{ &cpu::SLO, &cpu::add_ABS, 6 },
//         /* 1 */ { &cpu::BPL, &cpu::add_REL, 2 },{ &cpu::ORA, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SLO, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::ORA, &cpu::add_ZPX, 4 },{ &cpu::ASL, &cpu::add_ZPX, 6 },{ &cpu::SLO, &cpu::add_ZPX, 6 },{ &cpu::CLC, &cpu::add_IMP, 2 },{ &cpu::ORA, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SLO, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::ORA, &cpu::add_ABX, 4 },{ &cpu::ASL, &cpu::add_ABX, 7 },{ &cpu::SLO, &cpu::add_ABX, 7 },
//         /* 2 */ { &cpu::JSR, &cpu::add_ABS, 6 },{ &cpu::AND, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RLA, &cpu::add_iIND, 8 },{ &cpu::BIT, &cpu::add_ZP0, 3 },{ &cpu::AND, &cpu::add_ZP0, 3 },{ &cpu::ROL, &cpu::add_ZP0, 5 },{ &cpu::RLA, &cpu::add_ZP0, 5 },{ &cpu::PLP, &cpu::add_IMP, 4 },{ &cpu::AND, &cpu::add_IMM, 2 },{ &cpu::ROL, &cpu::add_IMP, 2 },{ &cpu::ANC, &cpu::add_IMP, 2 },{ &cpu::BIT, &cpu::add_ABS, 4 },{ &cpu::AND, &cpu::add_ABS, 4 },{ &cpu::ROL, &cpu::add_ABS, 6 },{ &cpu::RLA, &cpu::add_ABS, 6 },
//         /* 3 */	{ &cpu::BMI, &cpu::add_REL, 2 },{ &cpu::AND, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RLA, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::AND, &cpu::add_ZPX, 4 },{ &cpu::ROL, &cpu::add_ZPX, 6 },{ &cpu::RLA, &cpu::add_ZPX, 6 },{ &cpu::SEC, &cpu::add_IMP, 2 },{ &cpu::AND, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::RLA, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::AND, &cpu::add_ABX, 4 },{ &cpu::ROL, &cpu::add_ABX, 7 },{ &cpu::RLA, &cpu::add_ABX, 7 },
//         /* 4 */	{ &cpu::RTI, &cpu::add_IMP, 6 },{ &cpu::EOR, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SRE, &cpu::add_iIND, 8 },{ &cpu::NOP, &cpu::add_ZP0, 3 },{ &cpu::EOR, &cpu::add_ZP0, 3 },{ &cpu::LSR, &cpu::add_ZP0, 5 },{ &cpu::SRE, &cpu::add_ZP0, 5 },{ &cpu::PHA, &cpu::add_IMP, 3 },{ &cpu::EOR, &cpu::add_IMM, 2 },{ &cpu::LSR, &cpu::add_IMP, 2 },{ &cpu::ALR, &cpu::add_IMP, 2 },{ &cpu::JMP, &cpu::add_ABS, 3 },{ &cpu::EOR, &cpu::add_ABS, 4 },{ &cpu::LSR, &cpu::add_ABS, 6 },{ &cpu::SRE, &cpu::add_ABS, 6 },
//         /* 5 */ { &cpu::BVC, &cpu::add_REL, 2 },{ &cpu::EOR, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SRE, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::EOR, &cpu::add_ZPX, 4 },{ &cpu::LSR, &cpu::add_ZPX, 6 },{ &cpu::SRE, &cpu::add_ZPX, 6 },{ &cpu::CLI, &cpu::add_IMP, 2 },{ &cpu::EOR, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SRE, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::EOR, &cpu::add_ABX, 4 },{ &cpu::LSR, &cpu::add_ABX, 7 },{ &cpu::SRE, &cpu::add_ABX, 7 },
//         /* 6 */	{ &cpu::RTS, &cpu::add_IMP, 6 },{ &cpu::ADC, &cpu::add_iIND, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RRA, &cpu::add_iIND, 8 },{ &cpu::NOP, &cpu::add_ZP0, 3 },{ &cpu::ADC, &cpu::add_ZP0, 3 },{ &cpu::ROR, &cpu::add_ZP0, 5 },{ &cpu::RRA, &cpu::add_ZP0, 5 },{ &cpu::PLA, &cpu::add_IMP, 4 },{ &cpu::ADC, &cpu::add_IMM, 2 },{ &cpu::ROR, &cpu::add_IMP, 2 },{ &cpu::ARR, &cpu::add_IMP, 2 },{ &cpu::JMP, &cpu::add_IND, 5 },{ &cpu::ADC, &cpu::add_ABS, 4 },{ &cpu::ROR, &cpu::add_ABS, 6 },{ &cpu::RRA, &cpu::add_ABS, 6 },
//         /* 7 */	{ &cpu::BVS, &cpu::add_REL, 2 },{ &cpu::ADC, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::RRA, &cpu::add_INDi, 8 },{ &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::ADC, &cpu::add_ZPX, 4 },{ &cpu::ROR, &cpu::add_ZPX, 6 },{ &cpu::RRA, &cpu::add_ZPX, 6 },{ &cpu::SEI, &cpu::add_IMP, 2 },{ &cpu::ADC, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::RRA, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::ADC, &cpu::add_ABX, 4 },{ &cpu::ROR, &cpu::add_ABX, 7 },{ &cpu::RRA, &cpu::add_ABX, 7 },
//         /* 8 */	{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::STA, &cpu::add_iIND, 6 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SAX, &cpu::add_IMP, 6 }, { &cpu::STY, &cpu::add_ZP0, 3 },{ &cpu::STA, &cpu::add_ZP0, 3 },{ &cpu::STX, &cpu::add_ZP0, 3 },{ &cpu::SAX, &cpu::add_ZP0, 3 },{ &cpu::DEY, &cpu::add_IMP, 2 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::TXA, &cpu::add_IMP, 2 },{ &cpu::ANE, &cpu::add_IMP, 2 },{ &cpu::STY, &cpu::add_ABS, 4 },{ &cpu::STA, &cpu::add_ABS, 4 },{ &cpu::STX, &cpu::add_ABS, 4 },{ &cpu::SAX, &cpu::add_ABS, 4 },
//         /* 9 */	{ &cpu::BCC, &cpu::add_REL, 2 },{ &cpu::STA, &cpu::add_INDi, 6 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::SHA, &cpu::add_IMP, 6 }, { &cpu::STY, &cpu::add_ZPX, 4 },{ &cpu::STA, &cpu::add_ZPX, 4 },{ &cpu::STX, &cpu::add_ZPY, 4 },{ &cpu::SAX, &cpu::add_ZPX, 4 },{ &cpu::TYA, &cpu::add_IMP, 2 },{ &cpu::STA, &cpu::add_ABY, 5 },{ &cpu::TXS, &cpu::add_IMP, 2 },{ &cpu::TAS, &cpu::add_ABY, 5 },{ &cpu::SHY, &cpu::add_ABX, 5 },{ &cpu::STA, &cpu::add_ABX, 5 },{ &cpu::SHX, &cpu::add_ABY, 5 },{ &cpu::SHA, &cpu::add_ABY, 5 },
//         /* A */	{ &cpu::LDY, &cpu::add_IMM, 2 },{ &cpu::LDA, &cpu::add_iIND, 6 },{ &cpu::LDX, &cpu::add_IMM, 2 },{ &cpu::LAX, &cpu::add_IMP, 6 }, { &cpu::LDY, &cpu::add_ZP0, 3 },{ &cpu::LDA, &cpu::add_ZP0, 3 },{ &cpu::LDX, &cpu::add_ZP0, 3 },{ &cpu::LAX, &cpu::add_ZP0, 3 },{ &cpu::TAY, &cpu::add_IMP, 2 },{ &cpu::LDA, &cpu::add_IMM, 2 },{ &cpu::TAX, &cpu::add_IMP, 2 },{ &cpu::LXA, &cpu::add_IMP, 2 },{ &cpu::LDY, &cpu::add_ABS, 4 },{ &cpu::LDA, &cpu::add_ABS, 4 },{ &cpu::LDX, &cpu::add_ABS, 4 },{ &cpu::LAX, &cpu::add_ABS, 4 },
//         /* B */	{ &cpu::BCS, &cpu::add_REL, 2 },{ &cpu::LDA, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::LAX, &cpu::add_IMP, 5 }, { &cpu::LDY, &cpu::add_ZPX, 4 },{ &cpu::LDA, &cpu::add_ZPX, 4 },{ &cpu::LDX, &cpu::add_ZPY, 4 },{ &cpu::LAX, &cpu::add_ZPX, 4 },{ &cpu::CLV, &cpu::add_IMP, 2 },{ &cpu::LDA, &cpu::add_ABY, 4 },{ &cpu::TSX, &cpu::add_IMP, 2 },{ &cpu::LAS, &cpu::add_ABY, 4 },{ &cpu::LDY, &cpu::add_ABX, 4 },{ &cpu::LDA, &cpu::add_ABX, 4 },{ &cpu::LDX, &cpu::add_ABY, 4 },{ &cpu::LAX, &cpu::add_ABY, 4 },
//         /* C */	{ &cpu::CPY, &cpu::add_IMM, 2 },{ &cpu::CMP, &cpu::add_iIND, 6 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::DCP, &cpu::add_IMP, 8 }, { &cpu::CPY, &cpu::add_ZP0, 3 },{ &cpu::CMP, &cpu::add_ZP0, 3 },{ &cpu::DEC, &cpu::add_ZP0, 5 },{ &cpu::DCP, &cpu::add_ZP0, 5 },{ &cpu::INY, &cpu::add_IMP, 2 },{ &cpu::CMP, &cpu::add_IMM, 2 },{ &cpu::DEX, &cpu::add_IMP, 2 },{ &cpu::SBX, &cpu::add_IMP, 2 },{ &cpu::CPY, &cpu::add_ABS, 4 },{ &cpu::CMP, &cpu::add_ABS, 4 },{ &cpu::DEC, &cpu::add_ABS, 6 },{ &cpu::DCP, &cpu::add_ABS, 6 },
//         /* D */	{ &cpu::BNE, &cpu::add_REL, 2 },{ &cpu::CMP, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::DCP, &cpu::add_IMP, 8 }, { &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::CMP, &cpu::add_ZPX, 4 },{ &cpu::DEC, &cpu::add_ZPX, 6 },{ &cpu::DCP, &cpu::add_ZPX, 6 },{ &cpu::CLD, &cpu::add_IMP, 2 },{ &cpu::CMP, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::DCP, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::CMP, &cpu::add_ABX, 4 },{ &cpu::DEC, &cpu::add_ABX, 7 },{ &cpu::DCP, &cpu::add_ABX, 7 },
//         /* E */	{ &cpu::CPX, &cpu::add_IMM, 2 },{ &cpu::SBC, &cpu::add_iIND, 6 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::ISC, &cpu::add_IMP, 8 }, { &cpu::CPX, &cpu::add_ZP0, 3 },{ &cpu::SBC, &cpu::add_ZP0, 3 },{ &cpu::INC, &cpu::add_ZP0, 5 },{ &cpu::ISC, &cpu::add_ZP0, 5 },{ &cpu::INX, &cpu::add_IMP, 2 },{ &cpu::SBC, &cpu::add_IMM, 2 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::SBC, &cpu::add_IMP, 2 },{ &cpu::CPX, &cpu::add_ABS, 4 },{ &cpu::SBC, &cpu::add_ABS, 4 },{ &cpu::INC, &cpu::add_ABS, 6 },{ &cpu::ISC, &cpu::add_ABS, 6 },
//         /* F */	{ &cpu::BEQ, &cpu::add_REL, 2 },{ &cpu::SBC, &cpu::add_INDi, 5 },{ &cpu::JAM, &cpu::add_IMP, 2 },{ &cpu::ISC, &cpu::add_IMP, 8 }, { &cpu::NOP, &cpu::add_ZPX, 4 },{ &cpu::SBC, &cpu::add_ZPX, 4 },{ &cpu::INC, &cpu::add_ZPX, 6 },{ &cpu::ISC, &cpu::add_ZPX, 6 },{ &cpu::SED, &cpu::add_IMP, 2 },{ &cpu::SBC, &cpu::add_ABY, 4 },{ &cpu::NOP, &cpu::add_IMP, 2 },{ &cpu::ISC, &cpu::add_ABY, 7 },{ &cpu::NOP, &cpu::add_ABX, 4 },{ &cpu::SBC, &cpu::add_ABX, 4 },{ &cpu::INC, &cpu::add_ABX, 7 },{ &cpu::ISC, &cpu::add_ABX, 7 },

// //         //REMEMBER  A-0,2,4,6  ADD MODE A CHECK INSTRUCTION TABLE WEBSITE     
//         };

